### ISSUE TITLE
beta and SE from Z-score

### ISSUE THREAD

**Issue by andronekomimi** [BorgwardtLab/ARDISS#7]
Hi,

Thank you for your tool.
Once the imputation is completed, how can I get the beta and SE of each unmeasured marker?
Thank you

Best,
Audrey

**Comment by mtog** [comment]
Hi Audrey,

Thank you for your question. The z-scores are obtained by dividing beta by the standard error for each association. It is possible to retrieve betas from z-scores by using other association statistics such as p-values or allele frequencies, but I imagine you do not have access to these measures in your imputation scenario.

The easiest thing to do, in your scenario, is to directly impute betas and SEs. Betas, as association summary statistics, can be directly imputed in the same way as z-scores. We do so in an experiment in the referenced paper. You might want to mean center the typed values you already have and do an inverse transform after imputation for better results.

Let me know if you have any other question.
Matteo
